//! The global registry repo's `.gitignore`, and why bundled workflows are
//! kept out of it.
//!
//! The pm config dir can be git-backed (`pm state init --global`) so the
//! project registry, global config, and global *custom* workflows sync
//! between machines. The bundled workflows live in the same `workflows/`
//! dir, but they are pm's: `pm upgrade` rewrites them every release, and
//! committing that churn would make every machine's registry dirty after
//! each upgrade. So `.gitignore` carries a marker-delimited block naming
//! the bundled workflow dirs, regenerated from the bundle wherever bundled
//! workflows are written — never a hand-kept list, which would go stale.
//! Because the file is tracked, one machine's regeneration reaches the
//! others through the repo. Everything outside the block is the user's.
//!
//! Copies an earlier release committed are untracked in the same pass
//! (`git rm --cached`), staged but not committed: the next `pm state push
//! --global` commits the deletion, and a machine that pulls it loses the
//! dirs from disk until its own `pm upgrade` reinstalls them.

use std::path::{Path, PathBuf};

use crate::error::Result;
use crate::fs_utils::write_atomic;
use crate::git;
use crate::state::paths;

use super::skills::bundled_workflow_names;

/// Lines every registry `.gitignore` starts from. The project-level `.pm/`
/// needs no `.gitignore` because pm controls every file there; the registry
/// may accumulate machine-specific ephemera.
const BASE: &str = "\
# Ephemeral / machine-specific state
*.lock
*.pid
";

const BLOCK_START: &str =
    "# >>> bundled workflows — regenerated by pm, edit outside this block >>>";
const BLOCK_END: &str = "# <<< bundled workflows <<<";

fn gitignore_path(config_dir: &Path) -> PathBuf {
    config_dir.join(".gitignore")
}

fn block() -> String {
    let mut out = format!("{BLOCK_START}\n");
    for name in bundled_workflow_names() {
        out.push_str(&format!("/{}/{name}/\n", paths::WORKFLOWS_DIR_NAME));
    }
    out.push_str(BLOCK_END);
    out.push('\n');
    out
}

/// `existing` with its bundled block replaced (or appended when absent);
/// every line outside the block is kept. A block is a `BLOCK_START` whose
/// following lines are all workflow patterns up to a `BLOCK_END`; a start
/// marker without one is a user line and stays.
fn render(existing: Option<&str>) -> String {
    let lines: Vec<&str> = existing.unwrap_or(BASE).lines().collect();
    let block = block();
    let mut out = String::new();
    match find_block(&lines) {
        Some((start, end)) => {
            for l in &lines[..start] {
                out.push_str(l);
                out.push('\n');
            }
            out.push_str(&block);
            for l in &lines[end + 1..] {
                out.push_str(l);
                out.push('\n');
            }
        }
        None => {
            for l in &lines {
                out.push_str(l);
                out.push('\n');
            }
            if !out.is_empty() && !out.ends_with("\n\n") {
                out.push('\n');
            }
            out.push_str(&block);
        }
    }
    out
}

/// Indices of the first well-formed block's start and end markers.
fn find_block(lines: &[&str]) -> Option<(usize, usize)> {
    let prefix = format!("/{}/", paths::WORKFLOWS_DIR_NAME);
    for (start, line) in lines.iter().enumerate() {
        if *line != BLOCK_START {
            continue;
        }
        let body = lines[start + 1..]
            .iter()
            .take_while(|l| l.starts_with(&prefix) && l.ends_with('/'))
            .count();
        if lines.get(start + 1 + body) == Some(&BLOCK_END) {
            return Some((start, start + 1 + body));
        }
    }
    None
}

fn read_existing(config_dir: &Path) -> Result<Option<String>> {
    match std::fs::read_to_string(gitignore_path(config_dir)) {
        Ok(s) => Ok(Some(s)),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(e) => Err(e.into()),
    }
}

/// Write the registry `.gitignore` with the current bundled block, creating
/// it from the base ephemera list when absent. Returns whether the file
/// changed (would change, in `dry_run`, which writes nothing).
pub fn write_global_gitignore(config_dir: &Path, dry_run: bool) -> Result<bool> {
    let existing = read_existing(config_dir)?;
    let rendered = render(existing.as_deref());
    if existing.as_deref() == Some(rendered.as_str()) {
        return Ok(false);
    }
    if !dry_run {
        write_atomic(&gitignore_path(config_dir), rendered.as_bytes())?;
    }
    Ok(true)
}

/// Untrack every bundled workflow dir the registry repo has committed,
/// leaving the files on disk and the deletion staged. Returns the names
/// affected; nothing happens (and nothing is reported) without a repo.
pub fn untrack_bundled_workflows(config_dir: &Path, dry_run: bool) -> Result<Vec<String>> {
    if !git::is_git_repo(config_dir) {
        return Ok(Vec::new());
    }
    let mut names = Vec::new();
    for name in bundled_workflow_names() {
        let rel = format!("{}/{name}", paths::WORKFLOWS_DIR_NAME);
        if git::ls_files(config_dir, &rel)?.is_empty() {
            continue;
        }
        if !dry_run {
            git::rm_cached(config_dir, &rel)?;
        }
        names.push(name.to_string());
    }
    Ok(names)
}

/// Bring the registry repo's view of the bundled workflows up to date:
/// regenerate the ignore block and untrack committed copies. One
/// user-facing line per action taken (`Would …` in `dry_run`, which writes
/// nothing); nothing to do yields no lines.
pub fn sync_global_registry_ignore(config_dir: &Path, dry_run: bool) -> Result<Vec<String>> {
    let mut lines = Vec::new();
    if write_global_gitignore(config_dir, dry_run)? {
        let verb = if dry_run { "Would ignore" } else { "Ignored" };
        lines.push(format!(
            "{verb} bundled workflows in {}",
            gitignore_path(config_dir).display()
        ));
    }
    let untracked = untrack_bundled_workflows(config_dir, dry_run)?;
    if !untracked.is_empty() {
        let n = untracked.len();
        lines.push(if dry_run {
            format!("Would untrack {n} bundled workflow(s) from the global registry repo")
        } else {
            format!(
                "Untracked {n} bundled workflow(s) from the global registry repo \
                 (commit with `pm state push --global`)"
            )
        });
    }
    Ok(lines)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn ignored(config_dir: &Path, rel: &str) -> bool {
        std::process::Command::new("git")
            .args([
                "-C",
                &config_dir.to_string_lossy(),
                "check-ignore",
                "-q",
                rel,
            ])
            .status()
            .unwrap()
            .success()
    }

    fn marker_count(s: &str) -> usize {
        s.lines().filter(|l| *l == BLOCK_START).count()
    }

    #[test]
    fn write_creates_from_base_and_is_idempotent() {
        let dir = tempdir().unwrap();
        assert!(write_global_gitignore(dir.path(), false).unwrap());
        let first = std::fs::read_to_string(dir.path().join(".gitignore")).unwrap();
        assert!(first.starts_with(BASE));

        assert!(!write_global_gitignore(dir.path(), false).unwrap());
        let second = std::fs::read_to_string(dir.path().join(".gitignore")).unwrap();
        assert_eq!(first, second);

        git::init_repo(dir.path()).unwrap();
        for name in bundled_workflow_names() {
            assert!(ignored(
                dir.path(),
                &format!("workflows/{name}/config.toml")
            ));
        }
        assert!(!ignored(dir.path(), "workflows/mine/config.toml"));
        assert!(ignored(dir.path(), "foo.lock"));
    }

    #[test]
    fn write_keeps_user_lines_and_replaces_a_stale_block() {
        let dir = tempdir().unwrap();
        let stale =
            format!("scratch/\n\n{BLOCK_START}\n/workflows/old-name/\n{BLOCK_END}\ntrailing\n");
        std::fs::write(dir.path().join(".gitignore"), &stale).unwrap();

        assert!(write_global_gitignore(dir.path(), false).unwrap());
        let out = std::fs::read_to_string(dir.path().join(".gitignore")).unwrap();
        assert_eq!(marker_count(&out), 1);
        assert!(!out.contains("old-name"));
        assert!(out.starts_with("scratch/\n"));
        assert!(out.ends_with("trailing\n"));

        git::init_repo(dir.path()).unwrap();
        assert!(ignored(dir.path(), "scratch/x"));
        assert!(ignored(dir.path(), "trailing"));
        assert!(!ignored(dir.path(), "workflows/old-name/config.toml"));
        for name in bundled_workflow_names() {
            assert!(ignored(
                dir.path(),
                &format!("workflows/{name}/config.toml")
            ));
        }
    }

    #[test]
    fn write_keeps_lines_after_an_unclosed_block() {
        let dir = tempdir().unwrap();
        let mangled = format!("{BLOCK_START}\n/workflows/old-name/\nuser-line\n");
        std::fs::write(dir.path().join(".gitignore"), &mangled).unwrap();

        assert!(write_global_gitignore(dir.path(), false).unwrap());
        let out = std::fs::read_to_string(dir.path().join(".gitignore")).unwrap();
        assert!(out.starts_with(&mangled), "{out}");
        assert_eq!(out.lines().filter(|l| *l == BLOCK_END).count(), 1);

        // The stray start marker is now a user line: stable across rewrites.
        assert!(!write_global_gitignore(dir.path(), false).unwrap());
        assert_eq!(
            std::fs::read_to_string(dir.path().join(".gitignore")).unwrap(),
            out
        );
    }

    #[test]
    fn write_appends_block_to_a_file_without_one() {
        let dir = tempdir().unwrap();
        std::fs::write(dir.path().join(".gitignore"), "mine.txt").unwrap();
        assert!(write_global_gitignore(dir.path(), false).unwrap());
        let out = std::fs::read_to_string(dir.path().join(".gitignore")).unwrap();
        assert_eq!(marker_count(&out), 1);
        assert!(out.starts_with("mine.txt\n"));
        assert!(!write_global_gitignore(dir.path(), false).unwrap());
    }

    #[test]
    fn sync_without_a_repo_only_writes_the_gitignore() {
        let dir = tempdir().unwrap();
        let lines = sync_global_registry_ignore(dir.path(), false).unwrap();
        assert_eq!(lines.len(), 1, "{lines:?}");
        assert!(lines[0].starts_with("Ignored bundled workflows in "));
        assert!(
            sync_global_registry_ignore(dir.path(), false)
                .unwrap()
                .is_empty()
        );
    }

    #[test]
    fn dry_run_reports_without_writing() {
        let dir = tempdir().unwrap();
        let lines = sync_global_registry_ignore(dir.path(), true).unwrap();
        assert_eq!(lines.len(), 1, "{lines:?}");
        assert!(lines[0].starts_with("Would ignore"));
        assert!(!dir.path().join(".gitignore").exists());
    }
}
